name: Initialize TEI

on: 
  workflow_dispatch:

jobs:
  build_pages:
    name: Publish Edition TEI/XML
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Setup Java / Ant
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Install Ant
      run: |
        apt-get update && apt-get install ant -y --no-install-recommend
        wget https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download && unzip download -d saxon && rm -rf download
        ./scripts/sh/dl_saxon.sh
    - name: Install Ant-Contrib
      run: |
        wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
        mv ant-contrib-1.0b3.jar /usr/share/ant/lib
    - name: Fetch data
      run: |
        ./scripts/sh/fetch_data.sh
    - name: Build
      run: |
        ant -f scripts/ant/build.xml
    - name: Commit data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Downloaded/Updated Data
